### PR TITLE
Prepare for help files translation (issue #48)

### LINKED ISSUE #48: Translate help files?
Currently it consists of 47 strings to translate, and it would require the following changes:
- `./update-translations.sh` — also generate POT and update PO of help files
- `help/LINGUAS` — hold one language code per line; meson.build will read to build and install translated help
- `help/dynamic-wallpaper-editor.pot` — create using adapted update-translations.sh
- `CONTRIBUTING.md` — include instructions on translating help files

Are you interested in a pull request that enables translation of help files?

### PR DESCRIPTION
**Pull request by rffontenelle**
This:
- Create `help/LINGUAS` with no languages, just a comment
- Add `itstool` to `meson.build`, otherwise `ninja -C _build help-dynamic-wallpaper-editor-pot` and `...-update-po`command would fail
- Edit `CONTRIBUTING.md` to include help files translations.

Regarding, `CONTRIBUTING.md`, I moved instructions the would apply to both UI and Help translations into a introductory section, then specific instructions to subsections. This of course resulting in rewriting part of the previously existent instructions.

Sadly, `ninja -C _build help-dynamic-wallpaper-editor-update-po` will fail if the translation file does not exist. I tried without the directory (`help/LANG`), then created that directory without `.po` file, and finally with the `.po` file. Only the last try worked. So, manual creation is required. Copying pot to po is an option, but would require too much manual edit of gettext fields. I opted to suggest using `msginit`

Fixes #48

### CODE REVIEW

**Comment by maoschanz** [comment]
would it work if itstool was imported in `help/meson.build` instead?

if no, ok i'll merge it like it is now; if yes, could you change it, and include in your commit the following changes:

- comment above the itstool import to explain what it's for
- in contributing.md, "sections" instead of "sessions"
- replace "please test" by "you should test" (i don't really care if they don't test it, people should be able to contribute without putting tons of files on their disk, they're probably not even that interested in the app lol)

**Comment by rffontenelle** [comment]
I force-pushed to fix typo in commit message.

**Comment by rffontenelle** [comment]
hmm, I think I have a better testing command line for help files...

**Comment by rffontenelle** [comment]
The misspelling fix came from a git-rebase.

With last commit I added instructions that avoiding needing to run `meson` and then `ninja` to test help pages, and place the help pages in the very same directory, instead of in `/tmp`.  What do you say about it?

**Pull request merged**
